handle argument gas cost increasing since nightshade V2
referencedev/sputnik-dao-contract pull request #1
Opened 2024-08-24 08:11 UTC by marco-sundsk

As the gas cost of send_not_sir in `function_call_per_byte` increased greatly, check [here](https://github.com/near/nearcore/blob/0c2374993fc74b57faf2bcdf5c7c73a37e82b75a/core/parameters/res/runtime_configs/parameters.snap#L52) for detail, the leftover gas is insufficient for the receipt which creates the promise to pass large wasm code as aurgement in cross-contract calls, like this:  
```
env::promise_batch_action_function_call(
    promise_id,
    method_name,
    &input,
    NO_DEPOSIT,
    env::prepaid_gas() - env::used_gas() - GAS_FOR_UPGRADE_REMOTE_DEPLOY,
);
```
This PR is aiming to address that issue through increasing the gas leftover due to the size of passing wasm code.

2024-09-01 10:01 UTC, think-in-universe requested changes

2024-09-01 10:01 UTC, think-in-universe commented on sputnikdao2/src/upgrade.rs
> +pub const GAS_FUNCTION_CALL_PER_BYTE: u64 = 47_683_715;
I think we can update the constant to be more precise:

The gas cost per byte for cross-shard function call action is `47_683_715` (`send_not_sir`) + `2_235_934` (`execution`)  = `49_919_649`, close to 50TB per MB.

2024-09-02 00:59 UTC, think-in-universe commented on sputnikdao2/src/upgrade.rs
> +pub const GAS_FUNCTION_CALL_PER_BYTE: u64 = 47_683_715;
Oh, my bad, after second thought, here we should only charge the fees for sending the receipt, and don't need to include the execution gas cost, so I think the gas cost estimation is OK.

2024-09-03 11:36 UTC, referencedev approved these changes

2024-09-03 11:36 UTC, merged